[package]
name = "bitcoin-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
base58 = "0.1"
ripemd160 = "0.9"
secp256k1 = { version = "0.21", features = ["rand"] }
sha2 = "0.10"
k256 = "0.10"
bitcoin = "0.27"
